# Generated by Django 4.0.10 on 2024-05-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='doctor', max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'type': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='doctor_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='doctor_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'permissions': (('can_view_doctor', 'Can view doctor'),),
            },
        ),
    ]
