# Generated by Django 4.0.10 on 2024-05-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
