# Generated by Django 4.0.10 on 2024-05-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_app', '0004_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
